name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update build number
        uses: mclift/build-count-action@v0.4
        id: build-count-action
        with: 
          version-component: build

      - name: Get the New Version
        run: echo "New version is ${{ steps.build-count-action.outputs.new-version }}"
